version: '3.8'

services:

  web:
    build:
      context: .
      dockerfile: ./items_shop_web/Dockerfile
    restart: always
    container_name: web
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py collectstatic --noinput &&
             exec gunicorn core.wsgi:application -b 0.0.0.0:$WEB_PORT --log-level debug"
    volumes:
      - items_shop_web_static_value:/app/web-static/
      - items_shop_web_media_value:/app/web-media/
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    env_file:
      - .env

  db:
    image: postgres:15-alpine
    restart: always
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - items_shop_web_pgdata:/var/lib/postgresql/data/
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 80s

volumes:
  items_shop_web_pgdata:
    name: items_shop_web_pgdata
  items_shop_web_static_value:
    name: items_shop_web_static_value
  items_shop_web_media_value:
    name: items_shop_web_media_value
